### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by GabenGar** [turistu/totp-in-javascript#4]
There are no build instructions.

**Comment by turistu** [comment]
There's really nothing to "build" here; it's just html and javascript ;-)

Running [`make`](https://github.com/turistu/totp-in-javascript/blob/main/Makefile) will create the `totp.xpi` webextension by zipping 5 source files and the standalone [totp.html](https://turistu.github.io/totp.html) by concatenating the html, javascript and the README into a single file. That's all.

The [workflow](https://github.com/turistu/totp-in-javascript/blob/main/.github/workflows/push-html.yml) does all that automatically on each change.

**Comment by GabenGar** [comment]
Workflow is a github-only feature, so no thanks. `make` is also a Linux-only tool (on top the makefile itself calling a bunch of Linux-only commands), so it should be mentioned in the readme as a requirement. 
The scripts themselves use a bunch of browser-specific APIs and syntax with varying support, such as [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (which is firefox min version 74 btw, so the manifest file is wrong).
In general it doesn't make sense to build for extension and html at the same time, since they have wildly different target consumers: one is built for a specific browser vendor with specific version range and the other targets as many vendors and versions as it can, in this case implicitly. You should split the build into two makefiles for a start, even if they do the exactly the same thing (for now) and mention in readme how to run specific build commands.

**Comment by turistu** [comment]
> Workflow is a github-only feature, so no thanks. `make` is also a Linux-only tool (on top the makefile itself calling a bunch of Linux-only commands), so it should be mentioned in the readme as a requirement.

The only thing you require to start using my little hack the is this:
```
<input id=key>
<button id=gen>Generate TOTP</button>
<output id=code></output>
<script>
gen.onclick = function(){
        totp(key.value).then(c => code.value = c, e => code.value = e);
}
... paste totp.js here ....
</script>
```
The only thing you require to build the extension is `zip`, `jar` or any program who can pack 5 text files into a zip archive.

`make` is not a "Linux-only" tool (in fact, it predates Linux by at least 20 years), and the commands it calls aren't "Linux-only" either. 

> The scripts themselves use a bunch of browser-specific APIs and syntax with varying support, such as [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (which is firefox min version 74 btw, so the manifest file is wrong).

Optional chaining is only used in the `extra.js` example which is NOT included in the extension or in the standalone page. It's also [standard](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-OptionalExpression), not "browser-specific". I will not complicate that example just for the sake of making it compatible with IE 7 or whatever.

But I have corrected the manifest to set the minimum version to 67 (not 74); versions before that have some css problems when displaying the popup (and are not showing the correct toolbar icon either).

Could you please give other examples from that "bunch of browser-specific APIs and syntax"? 

> You should split the build into two makefiles for a start, even if they do the exactly the same thing (for now).

I would certainly not do such a thing LOL.

**Comment by GabenGar** [comment]
> The only thing you require to start using my little hack the is this:

Again, should be mentioned in the readme because it's not obvious what is and isn't included in the result just looking at the source code. And I'd rather consume build artifacts off locally installed dependencies directly instead of manually copying parts of html and then debugging it. Especially when dealing with anything cryptography.

> The only thing you require to build the extension is zip, jar or any program who can pack 5 text files into a zip archive.
- `set`
- `grep`
- `sed`
- `cat`
- `rm`
- `zip`
Nothing on this list is a thing on Windows. I guess `set` somewhat is, but uses windows-specific syntax, so `set -e` is not a thing on it.

> `make` is not a "Linux-only" tool (in fact, it predates Linux by at least 20 years), and the commands it calls aren't "Linux-only" either.

The repo setup absolutely requires Linux-only environment (implicitly) and won't work on a machine which existed 20 years prior Linux anyway.

> Optional chaining is only used in the `extra.js` example which is NOT included in the extension or in the standalone page. 

This being an example file is not obvious from the source code and isn't mentioned in the readme. Neither there are comments in the file indicating so. Also the "example" still requires a higher Firefox version than the source code, which might trip up the uninitiated. There is literally an [issue](https://github.com/turistu/totp-in-javascript/issues/2) which mentions firefox version incompatibility, but the version `88` is even higher than mentioned in this discussion and it's not obvious from the description if `88` is a min guessed by the person or considered outdated for the usage.

> It's also [standard](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-OptionalExpression), not "browser-specific". 

It being a standard has no relation to browser support (and therefore actually working). HTML Document Outline Algorithm was also in the HTML standard for ~10 years without a single implementation. Also I said `browser-specific APIs and syntax`, although the syntax in question is also browser-dependent, but on specific versions instead.

> I will not complicate that example just for the sake of making it compatible with IE 7 or whatever.

But you'll have to make it compatible with Safari, which is on the record of becoming the next IE. So far it looks like the build process for extension and plain html is needlessly coupled, despite the output environments differ greatly.  And both are tightly coupled to the browser javascript, despite what I assume the [main logic](https://github.com/turistu/totp-in-javascript/blob/main/totp.js) not even requiring browser APIs. This is all fixable and I might even be able to do it down the line, but first I need to know the output files, and therefore clear installation instructions.

> Could you please give other examples from that "bunch of browser-specific APIs and syntax"?

You mean review your code? Not gonna do it before looking at the output files first (which require clear installation instructions).

**Comment by turistu** [comment]
> > The only thing you require to build the extension is `zip`, `jar` or any program who can pack 5 text files into a zip archive.
> 
>     * `set`  * `grep`  * `sed` * `cat` * `rm`  * `zip`

WTF has *this* with *that* to do? Are you like, *sure* you're not ChatGPT or something?

> > Optional chaining is only used in the `extra.js` example which is NOT included in the extension or in the standalone page.
> 
> This being an example file is not obvious from the source code and isn't mentioned in the readme.

Ok, I've created a [branch](https://github.com/turistu/totp-in-javascript/tree/trimmed) without the `Makefile` and `extra.js` which are giving you so much trouble. Just fork that off and stop obsessing about that little Makefile.
 
> > It's also [standard](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-OptionalExpression), not "browser-specific".
> 
> > I will not complicate that example just for the sake of making it compatible with IE 7 or whatever.
> 
> But you'll have to make it compatible with Safari, which is on the record of becoming the next IE.

That example works fine on Safari (tested it on version 14.1.3 -- released more than 2 years ago). Optional chaining works fine on even older versions of safari. How about you doing some little fact-checking first?

> So far it looks like the build process for extension and plain html is needlessly coupled, despite the output environments differ greatly. And both are tightly coupled to the browser javascript

> despite what I assume the [main logic](https://github.com/turistu/totp-in-javascript/blob/main/totp.js) not even requiring browser APIs.

It *does* require a browser API, as mentioned prominently at the beginning of the very README you find so much lacking.

> > Could you please give other examples from that "bunch of browser-specific APIs and syntax"?
> 
> You mean review your code? Not gonna do it

Then just don't.
